### 동기적과 비동기적

작업을 동기적으로 처리한다면, 앞에 순서의 작업이 처리가 완료가 된 후에 다음 작업으로 넘어 갈 수 있다.

이렇게 작업을 진행하게 되면 선 작업이 완료되기 전까지 다른 작업을 못하기 때문에 불편하고 시간도 오래걸린다.

하지만 비동기적은 동시에 작업을 진행하기 때문에 다른 작업이 가능하며, 시간도 빠르다.



```react
function work() {
  const start = Date.now()
  for (let i = 0; i < 1000000000; i++) {}
  const end = Date.now()
  console.log(end - start + 'ms')
}

work();
console.log('다음 작업');

// 출력 순서
517ms
다음 작업
```



위 코드는 따로 어떤 비동기 작업을 하지않은 상태이다. 그러므로 ``work()`` 함수가 실행이 완료된뒤에야 ``다음 작업``이 출력 될수 있다.

만약 비동기적으로 작동하게 하고 싶다면, ``setTimeout()`` 이라는 함수를 사용해줘야 한다.

```react
function work() {
  setTimeout(() => {
    const start = Date.now()
    for (let i = 0; i < 1000000000; i++) {}
    const end = Date.now()
    console.log(end - start + 'ms')
  }, 0)
}

console.log('작업 시작');
work();
console.log('다음 작업');

// 출력 순서
작업 시작
다음 작업
508ms
```



``setTimeout``이라는 함수는 첫번째 파라미너에 넣는 함수를 두번째 파라미터에 넣은 시간(ms 단위)이 흐른 후 호출해 준다.

그런데, 만약에 work 함수가 끝난 다음에 어떤 작업을 처리하고 싶다면 어떻게 해야 할까?

이때는, 콜백 함수를 파라미터로 전달해주면 된다. **콜백 함수란, 함수 타입의 값을 파라미터로 넘겨줘서, 파라미터로 받은 함수를 특정 작업이 끝나면 호출해주는 것**을 의미한다.



```react
function work(callback) {
  setTimeout(() => {
    const start = Date.now()
    for (let i = 0; i < 1000000000; i++) {}
    const end = Date.now()
    console.log(end - start + 'ms')
    callback()
  }, 0)
}

console.log('작업 시작');
work(() => {
  console.log('작업이 끝났어요!')
});
console.log('다음 작업');
```

다음과 같은 작업들은 주로 비동기적으로 처리하게 된다.

- Ajax Web API 요청: 만약 서버쪽에서 데이터를 받아와야 할 때는, 요청을 하고 서버에 응답을 할 때 까지 대기를 해야 되기 때문에 작업을 비동기적으로 처리한다.
- 파일 읽기: 주로 서버 쪽에서 파일을 읽어야 하는 상황에는 비동기적으로 처리한다.
- 암호화/복호화: 암호화/복호화를 할 때에도 바로 처리가 되지 않고, 시간이 어느정도 걸리는 경우가 있기 때문에 비동기적으로 처리한다.
- 작업예약: 단순히 어떤 작업을 몇초 후에 스케줄링 해야 하는 상황에는, setTimeout을 사용하여 비동기적으로 처리한다



### Promise

프로미스는 비동기 작업을 보다 쉽고 편하게 사용하기 위해 ES6에 도입된 기능이다. 이전에는 비동기 작업을 처리 할 때에

 콜백 함수로 처리를 해왔다. 하지만, 콜백 함수로 처리를 하게 된다면 비동기 작업이 많아질 경우 코드가 쉽게 난잡해지게 된다.

(콜백 지옥)

비동기적으로 처리해야 하는 일이 많아질수록, 코드의 깊이가 계속 깊어지는 현상이 있는데, Promise를 사용하면 이렇게 코드의 깊이가 깊어지는 현상을 방지 할 수 있다.

Promise는 다음과 같이 만든다.

```react
const myPromise = new Promise((resolve, reject) => {
  // 구현..
})
```



Promise는 성공 할 수도 있고, 실패 할 수 도 있다. 성골할 때는 ``resolve`` 를 호출해주면 되고, 실패할 때에는

```reject``` 를 호출해주면 된다.

```react
const myPromise = new Promise((resolve, reject) => {
	setTimeout(() => {
    resolve(1)
  }, 1000)  
})

myPromise.then(n => {
  console.log(n)
})
```

resolve를 호출 할 때 특정 값을 파라미터로 넣어주면, 이 값을 작업이 끝나고 나서 사용할 수 있다.

작업이 끝나고 나서 또 다른 작업을 해야 할 때에는 Promise 뒤에, ``.then(...)`` 을 붙여서 사용하면 된다.



1초뒤에 실패되게끔 작성

```react
const myPromise = new Promise((resolve, reject) => {
  setTimeout(() => {
    reject(new Error())
  }, 1000)
})

myPromise
  .then(n => {
  	console.log(n)
	})
	.catch(error => {
  console.log(error)
})
```

실패하는 상황에서는 ``reject`` 를 사용하고, ``.catch``를 통하여 실패했을시 수행 할 작업을 설정 할 수 있다.

이제, Promise를 만드는 함수를 작성해 보자

```react
function increaseAndPrint(n) {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      const value = n + 1;
      if (value == 5) {
        const error = new Error();
        error.name = 'ValueIsFiveError';
        reject(error);
        return;
      }
      console.log(value)
      resolve(value)
    }, 1000)
  }) 
}

increaseAndPrint(0)
  .then((n) => {
  	return increaseAndPrint(n)
	})
	.then((n) => {
  	return increaseAndPrint(n)
	})
	.then((n) => {
  	return increaseAndPrint(n)
	})
	.then((n) => {
  	return increaseAndPrint(n)
	})
	.then((n) => {
  	return increaseAndPrint(n)
	})
	.catch(e => {
  	console.log(e)
	})

{/*
	위 코드는 이렇게 정리할 수 있다.
	increaseAndPrint(0)
		.then(increaseAndPrint)
		.then(increaseAndPrint)
		.then(increaseAndPrint)
		.then(increaseAndPrint)
		.then(increaseAndPrint)
		.catch(e => {
			console.error(e)
		})
*/}


//
1
2
3
4
ValueIsFiveError
```



**Promise를 사용하면, 비동기 작업의 개수가 많아져도 코드의 깊이가 깊어지지 않느다.**

하지만, 이것도 불편한 점이 있다. 에러를 잡을 때 몇번째에서 발생했는지 알아내기도 어렵고 특정 조건에 따라 분기를 나누는 작업도 어렵고, 특정 값을 공유해가면서 작업을 처리하기도 까다롭다. 이러한 문제점을 **async/await** 을 사용하면 해결할 수 있다.



### async/await

> async/await 문법은 ES8에 해당하는 문법으로서, Promise를 더욱 쉽게 사용 할 수 있게 해준다.



```react
function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

async function process() {
  console.log('안녕하세요');
  await sleep(1000); // 1초 쉬고
  console.log('반갑습니다.')
}

process();
```

async/await 문법을 사용할 때에는, 함수를 선언 할 때 함수의 앞부분에 ``async`` 키워드를 붙여줘야 한다. 그리고

Promise 의 앞부분에 ``await`` 을 넣어주면 해당 프로미스가 끝날때까지 기다렸다가 다음 작업을 수행 할 수 있다.

위 코드에서는 ``sleep`` 이라는 함수를 만들어서 파라미터로 넣어준 시간 만큼 기다리는 Promise를 만들고, 이를

``process`` 함수에서 사용해줬다.



함수에서 ``async`` 를 사용하면, 해당 함수는 결과값으로 Promise를 반환하게 된다. 따라서 다음과 같이 코드를 작성 할 수 있다.

```react
function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms)
}

                     
async function process() {
    console.log('안녕하세요!');
    await sleep(1000); // 1초 쉬고
 		console.log('반갑습니다!')   
}
  
process().then(() => {
  console.log('작업이 끝났어요!')
})
  
//
안녕하세요!
반갑습니다!
작업이 끝났어요!
```

``async`` 함수에서 에러를 발생 시킬때에는 ``throw``를 사용하고, 에러를 잡아낼 때에는 try/catch 문을 사용한다.

```react
function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms)
}
                     
async function makeError() {
	await sleep(1000);
  const error = new Error();
  throw error;
}

async function process() {
  try {
    await makeError();
  } catch (e) {
    console.error(e)
  }
}
  
process();
  
//
Error
```



이번에는, 비동기 함수를 몇개 더 만들어 보자.

```react
function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

const getDog = async () => {
  await sleep(1000);
  return '멍멍이';
};

const getRabbit = async () => {
  await sleep(500);
  return '토끼';
};

const getTurtle = async () => {
  await sleep(3000);
  return '거북이';
};

async function process() {
  const dog = await getDog();
  console.log(dog);
  const rabbit = await getRabbit();
  console.log(rabbit);
  const turtle = await getTurtle();
  console.log(turtle);
}
```

현재 위 코드에서는 ``getDog``는 1초, ``getRabbit``는 0.5초, ``getTurtle``은 3초가 걸린다. 이 함수들을 ``process`` 함수에서 연달아서 사용하게 되면서, ``process`` 함수가 실해되는 총 시간은 4.5초가 된다.

순서는 ``getDog`` -> ``getRabbit`` -> ``getTurtle``  순서대로 실행된다. 즉 하나가 끝나야 다음 작업이 시작된다.

만약, 동시에 작업하고 싶다면, 다음과 같이 ``promise.all`` 을 사용하면 된다.

```react
function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

const getDog = async () => {
  await sleep(1000);
  return '멍멍이';
};

const getRabbit = async () => {
  await sleep(500);
  return '토끼';
};

const getTurtle = async () => {
  await sleep(3000);
  return '거북이';
};

async function process() {
  const results = await Promise.all([getDog(), getRabbit(), getTurtle()]);
  console.log(results)
}

process();

//
['멍멍이', '토끼', '거북이']
```

만약에 여기서 배열 비구조화 할당 문법을 사용한다면 각 결과값을 따로 따로 추출해서 조회 할 수 있다.

```react
function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

const getDog = async () => {
  await sleep(1000);
  return '멍멍이';
};

const getRabbit = async () => {
  await sleep(500);
  return '토끼';
};

const getTurtle = async () => {
  await sleep(3000);
  return '거북이';
};

async function process() {
  const [dog, rabbit, turtle] = await Promise.all([
    getDog(),
    getRabbit(),
    getTurtle()
  ]);
  console.log(dog);
  console.log(rabbit);
  console.log(turtle);
}

process();

//
멍멍이
토끼
거북이
```

``Promise.all``를 사용 할 때에는, 등록한 프로미스 중 하나라도 실패하면, 모든게 실패 한 것으로 간주한다.

``Promise.race`` 는 ``Promise.all``과 달리, 여러개의 프로미스를 등록해서 실행했을 때 가장 빨리 끝난것 하나만의 결과값을 가져온다.

```react
function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

const getDog = async () => {
  await sleep(1000);
  return '멍멍이';
};

const getRabbit = async () => {
  await sleep(500);
  return '토끼';
};
const getTurtle = async () => {
  await sleep(3000);
  return '거북이';
};

async function process() {
  const first = await Promise.race([
    getDog(),
    getRabbit(),
    getTurtle()
  ])
  console.log(first)
}

process()

// 
토끼
```

``Promise.race`` 의 경우엔 가장 다른 Promise 가 먼저 성공하기 가장 먼저 끝난 Promise 가 실패하면 이를 실패로 간주한다. 따라서, 현재 위의 코드에서 ``getRabbit`` 에서 에러를 발생시킨다면 에러를 잡아낼 수 있지만, ``getTurtle`` 이난 ``getDog`` 에서 발생한 에러는 무시된다.





















